### ISSUE TITLE
not enough gaming 

### ISSUE THREAD

**Issue by JL0027** [TheNja09/Basics#1]

**Comment by Barabekeks** [comment]
I agreee

**Comment by JL0027** [comment]
based

**Comment by TheNja09** [comment]
Sorry for the inconvenience! Our staff team are on the problem right now, and there should be a hotfix patch withing 48-72 hours.

**Comment by JL0027** [comment]
> Sorry for the inconvenience! Our staff team are on the problem right now, and there should be a hotfix patch within 48-72 hours.

can't wait!!
